# -*- coding: utf-8 -*-
"""detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RC4yTlGsf5NxLhDe83je711VJAy85E61
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/sample_data/text.csv')

df.head(10)

df.shape

_,counts = np.unique(df['label'], return_counts=True)
print("Number of essays generated by AI: ", counts[1])
print("Number of essays written by Human: ", counts[0])
print("Total number of essays: ", df.shape[0])

"""## Data Analysis"""

df.describe()

# from transformers import AutoTokenizer

# tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
# df["tokens"] = df["text"].apply(lambda x: tokenizer.tokenize(x))

#df['tokens']

#df['text_length'] = df['text'].str.len()
from nltk.tokenize import sent_tokenize, word_tokenize
import gensim
from gensim.models import Word2Vec
corpus = 'n'.join(df[:10000]['text'])

print("Maximum number of characters in a single text row among the whole data frame: ", np.max(df['text_length']))

"""####Mean of text length for each label"""

print(df.groupby('label')['text_length'].mean())

"""Label distribution among different prompts."""

print(df.groupby('prompt_name')['label'].value_counts())

avg_text_length = df.groupby('label')['text_length'].mean()

plt.figure(figsize=(8, 6))
avg_text_length.plot(kind='bar', color=['skyblue', 'orange'], edgecolor='black')
plt.title('Average Text Length by Label', fontsize=16)
plt.xlabel('Label', fontsize=12)
plt.ylabel('Average Text Length', fontsize=12)
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.hist(df['text_length'], bins=30, color='skyblue', edgecolor='black')
plt.xlabel('Text Length (Number of Characters)', fontsize=12)
plt.ylabel('Frequency (Number of Texts)', fontsize=12)
plt.title('Distribution of Text Lengths', fontsize=15)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

from wordcloud import WordCloud
text = ' '.join(df['text'])
wordcloud = WordCloud(width=800, height=400).generate(text)
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

label_dist = df.groupby('prompt_name')['label'].value_counts().unstack()

# stacked bar chart
label_dist.plot(kind='bar', stacked=True, figsize=(12, 8), color=['skyblue', 'orange'])

plt.title('Label Distribution Across Prompts', fontsize=16)
plt.xlabel('Prompt Name', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.legend(title='Label', labels=['0', '1'], fontsize=10)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Vectorization"""

corpus = df['text']
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words='english')

#from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.metrics.pairwise import cosine_similarity

#vectorizer = TfidfVectorizer()
#tfidf_matrix = vectorizer.fit_transform(df['text'])

#X = vectorizer.fit_transform(corpus)
#y = df['label']

#from sklearn.model_selection import train_test_split
#X1_train, X1_test, y1_train, y1_test = train_test_split(X, y, test_size = 0.2)

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
est2 = LogisticRegression()
#est2.fit(X_train, y_train)
#y_pred = est2.predict(X_test)
#print("Accuracy: ", accuracy_score(y_test, y_pred))

from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=800)
X_reduced = svd.fit_transform(X)

#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X_reduced, y, test_size = 0.2)
#est2.fit(X_train, y_train)
#y_pred = est2.predict(X_test)
print("Accuracy: ", accuracy_score(y_test, y_pred))

variance = np.cumsum(svd.explained_variance_ratio_)*100

n_components = np.argmax(variance >= 87) + 1
print("Number of components that explain almost 87% of the variance: ", n_components)
#The SVD analysis explain that we need more components to explain more variance

from sklearn.tree import DecisionTreeClassifier, plot_tree
clf = DecisionTreeClassifier(max_depth=3)


clf.fit(X1_train, y1_train)

y1_pred = clf.predict(X1_test)


accuracy = accuracy_score(y1_test, y1_pred)
print("Accuracy:", accuracy)

plt.figure(figsize=(12, 8))

# Convert class names to strings
class_names = [str(c) for c in clf.classes_]

plot_tree(
    clf,
    feature_names=None,
    class_names=class_names,
    filled=True,
    rounded=True
)

plt.title("Decision Tree (Max Depth: 5)")
plt.show()

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(X1_train, y1_train)
rf_pred = rfc.predict(X1_test)
print("Accuracy using random forest classifier: ", accuracy_score(y1_test, rf_pred))

from sklearn.ensemble import AdaBoostClassifier
acf = AdaBoostClassifier(n_estimators=100, random_state=0)
acf.fit(X1_train, y1_train)

acf_pred = acf.predict(X1_test)
print("Accuracy score using adaboost: ", accuracy_score(y1_test, acf_pred))

"""Classification using MLP with sigmoid with reduced dimensions using SVD."""

from sklearn.neural_network import MLPClassifier
mcf = MLPClassifier(activation = 'logistic')
mcf.fit(X_train, y_train)

mcf_pred = mcf.predict(X_test)
print("Accuracy using Multi layer perceptron with sigmoid: ", accuracy_score(y_test, mcf_pred))

"""Classification using mlp with relu activation function."""

mcf_relu = MLPClassifier(activation="relu")
mcf_relu.fit(X_train, y_train)

mcf_relu_pred = mcf_relu.predict(X_test)
print("Accuracy using MLP with relu: ", accuracy_score(y_test, mcf_relu_pred))

"""Hyperparameter tuning using gridsearch."""

from sklearn.model_selection import GridSearchCV
from sklearn.utils import resample

X_small, y_small = resample(X_train, y_train, n_samples=10000, random_state=42)


param_grid = {
    'activation': ['relu', 'tanh'],
    'solver': ['adam', 'lbfgs'],
    'max_iter': [200, 500]
}


grid_search = GridSearchCV(estimator=mcf_relu, param_grid=param_grid, cv=3, scoring='accuracy')
grid_search.fit(X_small, y_small)


print("Best Parameters:", grid_search.best_params_)

grid_search.best_score_

from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

scores = cross_val_score(mcf_relu, X_train, y_train, cv=5, scoring='accuracy')

print("Cross-Validation Scores:", scores)
print("Mean Accuracy:", scores.mean())
print("Standard Deviation:", scores.std())